---
abstract: 'Miniature Model Organism Sequence Aligner'
author:
  - "Jonathan \"Duke\" Leto <jonathan@leto.net>"
build_requires:
  Catalyst::Test: 0
  HTML::Lint: 0
  HTML::Tagset: 3.20
  Test::DBIx::Class: 0
  Test::JSON: 0.11
  Test::Most: 0
  Test::WWW::Mechanize::Catalyst: 0.56
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Mimosa
provides:
  App::Mimosa:
    file: lib/App/Mimosa.pm
    version: 0.02
  App::Mimosa::Aligner:
    file: lib/App/Mimosa/Aligner.pm
    version: 0
  App::Mimosa::Controller::Auth:
    file: lib/App/Mimosa/Controller/Auth.pm
    version: 0
  App::Mimosa::Controller::JSON:
    file: lib/App/Mimosa/Controller/JSON.pm
    version: 0
  App::Mimosa::Controller::Root:
    file: lib/App/Mimosa/Controller/Root.pm
    version: 0
  App::Mimosa::Controller::Sequence:
    file: lib/App/Mimosa/Controller/Sequence.pm
    version: 0
  App::Mimosa::Database:
    file: lib/App/Mimosa/Database.pm
    version: 0
  App::Mimosa::Job:
    file: lib/App/Mimosa/Job.pm
    version: 0
  App::Mimosa::Model::BCS:
    file: lib/App/Mimosa/Model/BCS.pm
    version: 0
  App::Mimosa::Schema::BCS:
    file: lib/App/Mimosa/Schema/BCS.pm
    version: 0
  App::Mimosa::Schema::BCS::Result::Mimosa::Job:
    file: lib/App/Mimosa/Schema/BCS/Result/Mimosa/Job.pm
    version: 0
  App::Mimosa::Schema::BCS::Result::Mimosa::SequenceSet:
    file: lib/App/Mimosa/Schema/BCS/Result/Mimosa/SequenceSet.pm
    version: 0
  App::Mimosa::Schema::BCS::Result::Mimosa::SequenceSetOrganism:
    file: lib/App/Mimosa/Schema/BCS/Result/Mimosa/SequenceSetOrganism.pm
    version: 0
  App::Mimosa::Util:
    file: lib/App/Mimosa/Util.pm
    version: 0
  App::Mimosa::View::Mason:
    file: lib/App/Mimosa/View/Mason.pm
    version: 0
  App::Mimosa::View::SeqIO:
    file: lib/App/Mimosa/View/SeqIO.pm
    version: 0
requires:
  Bio::BLAST::Database: 0.2
  Bio::Chado::Schema: 0.08100
  Bio::GMOD::Blast::Graph: 0.05
  Bio::Root::Version: 1.006009
  Catalyst::Action::RenderView: 0
  Catalyst::Authentication::Store::DBIx::Class: 0
  Catalyst::Controller::REST: 0
  Catalyst::Model::DBIC::Schema: 0.48
  Catalyst::Plugin::Authentication: 0.10016
  Catalyst::Plugin::Authorization::Roles: 0
  Catalyst::Plugin::AutoCRUD: 1.110731
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::FastMmap: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: 5.80029
  Catalyst::View::Bio::SeqIO: 0
  Catalyst::View::Email: 0
  Catalyst::View::HTML::Mason: 0
  Class::Accessor::Fast: 0
  Config::JFDI: 0
  DBIx::Class: 0.08127
  DateTime: 0
  Digest::SHA1: 0
  File::Slurp: 9999.15
  File::Temp: 0
  HTML::Entities: 0
  IO::String: 0
  IPC::Cmd: 0.70
  IPC::Run: 0
  IPC::System::Simple: 0
  JSON::Any: 1.25
  Moose: 1.19
  Path::Class: 0
  SQL::Translator: 0.11007
  Set::Scalar: 0
  YAML: 0
  aliased: 0
  autodie: 2.00
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/gmod/mimosa/tree/master
version: 0.02
